project:
  type: website
  output-dir: docs

website:
  title: "Sophie Sees Wildlife"
  site-url: https://sophieseeswildlife.com
  description: An archive of my college wildlife sightings.
  navbar:
    right:
      - icon: house
        href: index.qmd
      - about.qmd
      - icon: instagram
        href: https://www.instagram.com/sophieabrea/
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css

editor: visual

